### ISSUE TITLE
shaders.properties program toggles are not supported

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#1026]
These are declarations of the form:

```
program.world0/deferred1.enabled = HBAO || RSM
```

**Comment by coderbot16** [comment]
Fixed in 1.5.0

**Comment by IMS212** [comment]
This is not fixed. JCPP can't properly preprocess multiple values at once.
