### ISSUE TITLE
Lava does not render correctly when using TME

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1050]
### What happened?

The lava is weird with TME (it looks like a Z fighting) (work properly towards the south east)

### Screenshots

Optifine:
![2021-12-04_22 25 00](https://user-images.githubusercontent.com/68275908/144725115-5c5fbcb2-ce41-4cd9-be1e-bb1e718c56e8.png)

Iris:
![2021-12-04_22 26 04](https://user-images.githubusercontent.com/68275908/144725119-13d4b987-56dd-4505-8c72-bd387d9154f1.png)

### Relevant log output

```shell
[22:26:00] [Render thread/WARN]: Program link log for composite: Vertex info
-----------
0(530) : warning C7050: "nsunlight" might be used before being initialized

[22:26:00] [Render thread/WARN]: Program link log for composite1: Vertex info
-----------
0(530) : warning C7050: "nsunlight" might be used before being initialized

[22:26:00] [Render thread/WARN]: Program link log for composite2: Vertex info
-----------
0(530) : warning C7050: "nsunlight" might be used before being initialized

[22:26:00] [Render thread/WARN]: Program link log for composite3: Vertex info
-----------
0(530) : warning C7050: "nsunlight" might be used before being initialized

[22:26:00] [Render thread/WARN]: Program link log for composite4: Vertex info
-----------
0(534) : warning C7050: "nsunlight" might be used before being initialized

[22:26:00] [Render thread/WARN]: Program link log for composite5: Vertex info
-----------
0(534) : warning C7050: "nsunlight" might be used before being initialized

[22:26:00] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[22:26:00] [Render thread/WARN]: Program link log for final: Vertex info
-----------
0(534) : warning C7050: "nsunlight" might be used before being initialized

[22:26:00] [Render thread/INFO]: Stopping worker threads
[22:26:00] [Render thread/INFO]: Started 6 worker threads
[22:26:00] [Render thread/WARN]: Program link log for sodium:chunk_shader_for_gbuffers_terrain: Vertex info
-----------
0(540) : warning C7050: "tangent" might be used before being initialized
0(541) : warning C7050: "binormal" might be used before being initialized

[22:26:00] [Render thread/WARN]: Program link log for sodium:chunk_shader_for_gbuffers_terrain_cutout: Vertex info
-----------
0(540) : warning C7050: "tangent" might be used before being initialized
0(541) : warning C7050: "binormal" might be used before being initialized
```

### Iris and Minecraft Version

iris-1.18-1.1.3

### Are you running Sodium along with Iris?

Yes

### Operating System

Ubuntu 20.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by Lolothepro** [comment]
![2021-12-05_08 31 06](https://user-images.githubusercontent.com/68275908/144737981-dd11dfcf-c0cc-4d76-ae14-ba7a9a760334.png)
![2021-12-05_08 32 53](https://user-images.githubusercontent.com/68275908/144737985-b172f3a5-0c83-4c8c-9974-5c98a34c13ad.png)

**Comment by Lolothepro** [comment]
as you can see on this screen, there are also some on the signs

**Comment by Lolothepro** [comment]
![2021-12-05_08 44 08](https://user-images.githubusercontent.com/68275908/144738244-25aee096-1ff0-4035-a48d-8a5c8dc6bf90.png)

**Comment by coderbot16** [comment]
Can you confirm that this is fixed in the latest test builds on the discord?

**Comment by Lolothepro** [comment]
https://github.com/IrisShaders/Iris/issues/1050#issuecomment-986182372 Fixed
https://github.com/IrisShaders/Iris/issues/1050#issue-1071299276 Not fixed
![2022-03-01_09 28 50](https://user-images.githubusercontent.com/68275908/156133298-68413bfb-880e-42b1-92a4-414a84f61855.png)
![2022-03-01_09 31 02](https://user-images.githubusercontent.com/68275908/156133304-b2dda9fe-31f7-4343-9c8e-5c8b7cdc0212.png)

**Comment by Lolothepro** [comment]
I can't reproduce it.
