### ISSUE TITLE
When multiple people use fishing rods, an additional black line is drawn (even with shaders turned off)

### ISSUE THREAD

**Issue by WerDei** [IrisShaders/Iris#1055]
### What happened?

One player casts a fishing rod, which draws a line from the end of a rod to the bobber, as expected. When a second player casts, it draws the expected line as well as an extra, straight black line from one player's bobber to the other's fishing rod.

Not captured in screenshot, but as more players join in, more lines appear. 

The line is always drawn from the oldest cast fishing rod to the newer bobber, then from that player's rod to the bobber next in the age order, and so on.

The issue is not with Sodium, tested it by removing only Iris (no extra lines appear then)

### Screenshots

![2021-12-05_00 11 52](https://user-images.githubusercontent.com/48105614/144768881-c3a2b51f-dd64-4af3-9ab7-679112e76fa6.png)
![2021-12-05_00 11 40](https://user-images.githubusercontent.com/48105614/144769025-552e1bde-6810-490c-9728-8d789532ad0f.png)

### Relevant log output

```shell
N/A
```

### Iris and Minecraft Version

iris-mc1.18-1.1.3.jar for 1.18, also had this issue with iris-and-sodium-mc1.17-1.1.2+build.9.jar in 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce GTX 1050 (dedicated), Intel(R) UHD Graphics 630 (integrated) 

### Java Version

Java 17 (Microsoft jdk-17.0.1.12-hotspot)

**Comment by IMS212** [comment]
This is highly likely to be the same issue as with leads that was worked around in BER, but the same workaround does not seem to work for this.

**Comment by jlucaso1** [comment]
> 

same here

**Comment by Smolax** [comment]
I have same situation

**Comment by coderbot16** [comment]
Bug does not happen on 1.16.5. Must be a 1.17+ issue introduced in the port.

![image](https://user-images.githubusercontent.com/22420959/167484360-39909f54-bc11-4e8d-92bd-ad415ea02e2f.png)

**Comment by WarmIceCream** [comment]
I've also been having this issue playing 1.18.2

**Comment by Gabe2008** [comment]
Will this be fixed in the next update

**Comment by CorbinCrow** [comment]
I have the same situation. Playing on Minecraft version 1.19.0

**Comment by jcodyparker** [comment]
This issue still exists. Please fix it so I can use Iris again

**Comment by jcodyparker** [comment]
Bump

**Comment by IMS212** [comment]
unbumped

This issue is very hard to fix properly. We don't want to go with a "half-done" fix that doesn't actually solve the problem.

The problem lies with how MC does lines. They're not actual lines, but 2 triangles posing as lines. This makes them smoother but makes them naturally want to connect. There's no "easy" way to disconnect them.

**Comment by dopadream** [comment]
You'll still try to fix it though, right?

**Comment by csaki01** [comment]
;-;

**Comment by IMS212** [comment]
It will indeed get fixed when we find a fix. If someone finds a fix that does not involve disabling batching, feel free to PR it.

**Comment by dopadream** [comment]
is there any way I can temporarily fix this for myself? its really annoying

**Comment by jcodyparker** [comment]
> is there any way I can temporarily fix this for myself? its really annoying

Basically just don't use iris at this point. I just have to play without shaders when fishing because the server I play on has a fishing event a few times a day and it looks terrible with iris. It really sucks because I wan't to use replay mod with shaders for this fishing event but I can't. If someone can think of a workaround to using replay mod with shaders without this issue please let me know. I tried to use optifine instead, but optifine doesnt show handheld items now for some reason so I cant even do that.

![image](https://user-images.githubusercontent.com/90956620/192627672-839d401f-59ab-45ba-a497-6420cb63c490.png)

**Comment by IMS212** [comment]
A potential fix is being tested on our discord; more testing needs to be done to evaluate whether the potential fix actually functions on all devices.

**Comment by IMS212** [comment]
If testing does well, a fix will be pushed soon.

**Comment by IMS212** [comment]
Fixed by https://github.com/IrisShaders/Iris/commit/e4f6082921ee631fd74485d12875a8b157aadf9d.

**Comment by IMS212** [comment]
Fixed in 1.4.
