### ISSUE TITLE
PTGI HRR Test doesn't work on AMD windows drivers

### ISSUE THREAD

**Issue by Zhuzi-ouo** [IrisShaders/Iris#1071]
### What happened?

PTGI HRR Test doesn't work on Rx 470
and PTGI E12 lighting have some problem

### Screenshots

![image](https://user-images.githubusercontent.com/85818541/145604007-562655b4-06d9-4d6b-a307-b93aa6467431.png)
![image](https://user-images.githubusercontent.com/85818541/145604068-9beb2a5e-258e-4a6a-9d84-caffdffa6381.png)
![image](https://user-images.githubusercontent.com/85818541/145604687-da7641ea-2708-44c5-84f4-2f04a35e559d.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.3 with Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 11

### What is your GPU?

AMD Rx 470 4GB

### Java Version

Java 16

**Comment by coderbot16** [comment]
We need a log file - HRR works fine on my machine.

**Comment by Zhuzi-ouo** [comment]
[2021-12-11-2.log](https://github.com/IrisShaders/Iris/files/7698189/2021-12-11-2.log)

**Comment by IMS212** [comment]
the actually relevant part of log (for some reason your log is insanely big) `[15:36:33] [Render thread/WARN]: Shader compilation log for composite5.fsh: Fragment shader failed to compile with the following errors:
ERROR: 0:1286: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:1286: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:1838: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:1838: error(#247) Function return does not match type
ERROR: 0:2973: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2973: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:2974: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2974: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:2975: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2975: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:3017: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:3017: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:3018: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:3018: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:3026: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:3118: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:3118: error(#216) Vector field selection out of range "rgb"
ERROR: 0:3999: error(#101) Macro redefined: FxaaInt2
ERROR: 0:4001: error(#101) Macro redefined: FxaaTexTop
ERROR: 0:4002: error(#101) Macro redefined: FxaaTexOff
ERROR: 0:4013: error(#101) Macro redefined: FxaaInt2
ERROR: 0:4013: error(#132) Syntax error: "sampler2D" parse error
ERROR: error(#273) 22 compilation errors.  No code generated

`

**Comment by Zhuzi-ouo** [comment]
[15:35:12] [Render thread/INFO]: Using shaderpack: SEUS PTGI HRR Test 2.1.zip
[15:35:12] [Render thread/INFO]: Creating pipeline OVERWORLD
[15:35:15] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[15:35:16] [Render thread/WARN]: Shader compilation log for composite5.fsh: Fragment shader failed to compile with the following errors:
ERROR: 0:1286: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:1286: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:1838: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:1838: error(#247) Function return does not match type
ERROR: 0:2973: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2973: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:2974: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2974: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:2975: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:2975: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:3017: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:3017: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:3018: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:3018: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:3026: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:3118: error(#203) More than one matching overloaded function are found: texture2DLod
ERROR: 0:3118: error(#216) Vector field selection out of range "rgb"
ERROR: 0:3999: error(#101) Macro redefined: FxaaInt2
ERROR: 0:4001: error(#101) Macro redefined: FxaaTexTop
ERROR: 0:4002: error(#101) Macro redefined: FxaaTexOff
ERROR: 0:4013: error(#101) Macro redefined: FxaaInt2
ERROR: 0:4013: error(#132) Syntax error: "sampler2D" parse error
ERROR: error(#273) 22 compilation errors.  No code generated


[15:35:16] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:233) ~[iris-mc1.17-1.1.3-starline+build.665.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:91) ~[iris-mc1.17-1.1.3-starline+build.665.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:211) ~[iris-mc1.17-1.1.3-starline+build.665.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:424) ~[iris-mc1.17-1.1.3-starline+build.665.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:32) [iris-mc1.17-1.1.3-starline+build.665.jar:?]
	at net.minecraft.class_761.handler$zjn000$iris$beginLevelRender(class_761.java:6316) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1129) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.5.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program composite5.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:98) ~[iris-mc1.17-1.1.3-starline+build.665.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:69) ~[iris-mc1.17-1.1.3-starline+build.665.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:229) ~[iris-mc1.17-1.1.3-starline+build.665.jar:?]
	... 18 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:44) ~[iris-mc1.17-1.1.3-starline+build.665.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:23) ~[iris-mc1.17-1.1.3-starline+build.665.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:96) ~[iris-mc1.17-1.1.3-starline+build.665.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:69) ~[iris-mc1.17-1.1.3-starline+build.665.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:229) ~[iris-mc1.17-1.1.3-starline+build.665.jar:?]
	... 18 more

**Comment by Ryan44444444444444444444444444444444444** [comment]
I have the same exact issue with my 6700xt

**Comment by bensuperpc** [comment]
I have same issues:
```
[12:35:35] [Render thread/INFO]: Destroying pipeline OVERWORLD
[12:35:36] [Render thread/WARN]: Error while parsing the block ID map entry "heavy_weighted_pressure_plate:powered=false":
[12:35:36] [Render thread/WARN]: - The block minecraft:heavy_weighted_pressure_plate has no property with the name powered, ignoring!
[12:35:36] [Render thread/WARN]: Error while parsing the block ID map entry "heavy_weighted_pressure_plate:powered=true":
[12:35:36] [Render thread/WARN]: - The block minecraft:heavy_weighted_pressure_plate has no property with the name powered, ignoring!
[12:35:36] [Render thread/INFO]: Using shaderpack: SEUS PTGI HRR 3.zip
[12:35:36] [Render thread/INFO]: Creating pipeline OVERWORLD
[12:35:36] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[12:35:36] [Render thread/WARN]: Program link log for composite5: Fragment info
-------------
0(5772) : warning C7050: "col" might be used before being initialized

[12:35:36] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[12:35:36] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
net.minecraft.class_2973: Invalid shaders/core/gbuffers_sky_basic.json: Couldn't compile fragment program (<iris shaderpack shaders>, gbuffers_sky_basic) : 0(3159) : error C1503: undefined variable "MC_RENDER_STAGE_STARS"
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.7) ~[?:?]
	at net.minecraft.client.gl.ShaderParseException.wrap(ShaderParseException:48) ~[?:?]
	at net.minecraft.client.render.Shader.<init>(Shader:200) ~[?:?]
	at net.coderbot.iris.pipeline.newshader.ExtendedShader.<init>(ExtendedShader.java:32) ~[iris-mc1.18.1-1.1.3.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewShaderTests.create(NewShaderTests.java:114) ~[iris-mc1.18.1-1.1.3.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:381) ~[iris-mc1.18.1-1.1.3.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:374) ~[iris-mc1.18.1-1.1.3.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:293) ~[iris-mc1.18.1-1.1.3.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:427) ~[iris-mc1.18.1-1.1.3.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:32) ~[iris-mc1.18.1-1.1.3.jar:?]
	at net.minecraft.client.render.WorldRenderer.handler$bef000$iris$beginLevelRender(WorldRenderer:8450) ~[?:?]
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1240) ~[?:?]
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1031) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:811) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.io.IOException: Couldn't compile fragment program (<iris shaderpack shaders>, gbuffers_sky_basic) : 0(3159) : error C1503: undefined variable "MC_RENDER_STAGE_STARS"
	at net.minecraft.client.gl.Program.loadProgram(Program:72) ~[?:?]
	at net.minecraft.client.gl.Program.createFromResource(Program:54) ~[?:?]
	at net.minecraft.client.render.Shader.loadProgram(Shader:241) ~[?:?]
	at net.minecraft.client.render.Shader.<init>(Shader:183) ~[?:?]
	... 29 more
[12:35:36] [Render thread/INFO]: Stopping worker threads
[12:35:36] [Render thread/INFO]: Started 10 worker threads
Clipboard copy at: 24 Dec 2021 12:35:43 +0100
MultiMC: Log upload triggered at: 24 Dec 2021 12:35:47 +0100
```

**Comment by M4rtinOF** [comment]
Same thing with RX 580 2048SP

**Comment by Daktyl198** [comment]
This still appears to be a problem:
```
[12:58:43] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:238) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:95) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:220) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:642) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:584) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:27) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:473) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$2(ShaderPackScreen.java:218) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:120) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:172) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:491) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) [lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204) [client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1171) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program deferred.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:78) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:234) ~[iris-mc1.19.1-1.2.6.jar:?]
	... 30 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:40) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:21) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:76) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-mc1.19.1-1.2.6.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:234) ~[iris-mc1.19.1-1.2.6.jar:?]
	... 30 more
```

**Comment by M4rtinOF** [comment]
Issue Fixed with new AMD Driver 22.7.1

**Comment by Daktyl198** [comment]
I'm on driver 22.7.1 and HRR 2.1 "works", but has shadow issues, and HRR 3 still fails entirely.

**Comment by maximumpower55** [comment]
> I'm on driver 22.7.1 and HRR 2.1 "works", but has shadow issues, and HRR 3 still fails entirely.

This is correct, exact same happens for me on the new driver, we already know about the shadow issue, but we don't know if its a issue with SEUS or iris since no body has tested to see if it happens on optifine yet.

**Comment by Daktyl198** [comment]
I've tested on Optifine for 1.19, and 1.19.1 with approximately the same results, and said results are kind of inconclusive.

Basically, the shaders are broken, but I still can't tell if it's SEUS's fault. HRR2.1 has some shadows working (more than Iris did) but some shadows are too dark. It also has texture artifacts on half of every block face. HRR3 doesn't work at all, but also doesn't throw any errors that I can see. It just renders pure black.

What's dumb is that Optifine's own (internal) shaders has the same texture artifacts I stated HRR2.1 had, so I can't blame that one on PTGI. I am unsure if Optifine is currently experience a bug with shaders on 1.19, never got it working to begin with, or just never updated their (internal) shaders to be compatible with new code.

I've attached 2 images, one is the (internal) shaders of Optifine, and the other is HRR2.1. As I said, HRR3 was just a black screen, so not much to show there with a screenshot
### (Internal)
![(internal)](https://user-images.githubusercontent.com/2475672/183273505-50061459-e4a0-4799-95ca-19c34d581d30.png)
### HRR 2.1
![HRR 2 1](https://user-images.githubusercontent.com/2475672/183273507-bd5b0508-3ed2-49b5-8ecf-e91d14ab6624.png)
.

**Comment by maximumpower55** [comment]
Those texture artifacts are a incompatible with optifine 1.19 / 1.19.1 and forge
Try with optifine just standalone

**Comment by Daktyl198** [comment]
Tested on non-forge Optifine 1.19, as well as forge Optifine 1.18.2.

HRR3 is still just straight up borked. HRR2.1 works, though there are clearly some signs of aging or incompatibility. The lighting and shadows work fine in general. I've attached some screenshots of the only issue I found, which is lighting seemingly coming from blocks that shouldn't have it.

### Grass blocks behaving weird
![2022-08-06_23 46 27](https://user-images.githubusercontent.com/2475672/183274473-ab94ad21-aa51-413c-bfc4-278e9af0b31c.png)
### Light underwater in a completely underground cave
![2022-08-06_23 49 38](https://user-images.githubusercontent.com/2475672/183274475-2939871e-fc44-43be-b3a8-0bb089887cc2.png)

**Comment by coderbot16** [comment]
Does this issue still occur on Iris 1.4 and above?

**Comment by rbcoder117** [comment]
I think I figured out the issue, its that RX cards arent supported for Seus
