### ISSUE TITLE
Shaders not applying in game

### ISSUE THREAD

**Issue by A-noximous** [IrisShaders/Iris#1093]
### What happened?

Shaders do not apply in game despite enabling and refreshing many times. Tested with ComplementaryShaders_v4.1. Same shaders have run successfully in 1.17.1.

### Screenshots

None

### Relevant log output

[File](https://github.com/IrisShaders/Iris/files/7708852/iris.log)

### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-1.1.3

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Operating System

Windows 10

### What is your GPU?

Intel HD Graphics 530

### Java Version

Java 17

### Additional context

The same shaders have worked previously in 1.17.1. The only thing changed(apart from the game version) is adding a few more mods. The full list is below:
Client Commands*
Continuity*
Fabric API
Carpet Mod
Indium*
Iris
LazyDFU*
Litematica
MaLiLib
MiniHUD
ModMenu
Nylon(Custom mod by me, should not cause issues, still the source is [here](https://github.com/A-noximous/nylon/))*
OkZoomer
Sodium
Tweakeroo

"*" indicates added for 1.18

Please let me know if any of these mods are incompatible and are causing the issue

**Comment by coderbot16** [comment]
We can't do anything without a log file, please attach one.

**Comment by A-noximous** [comment]
Sorry for the delay, have added the log file.

**Comment by coderbot16** [comment]
Ah, I see the issues, both are fixed in the next release. In the mean time, delete your `.minecraft/patched_shaders` folder. Also make sure you're running only one instance of the game.

**Comment by A-noximous** [comment]
I am running only one instance of the game, thanks for the info. Will confirm if deleting the folder fixes the issue.

**Comment by A-noximous** [comment]
I deleted the folder and restarted the game, still the same issue. Will have to wait for the next release. Thanks for addressing this.

**Comment by coderbot16** [comment]
You're welcome. For reference, this is the commit addressing the issue: https://github.com/IrisShaders/Iris/commit/ff4261c1ac4bf97d9eac759c85115212e81056e5

**Comment by A-noximous** [comment]
Any ETA on the release with the fix?

> Ah, I see the issues, both are fixed in the next release. In the mean time, delete your `.minecraft/patched_shaders` folder. Also make sure you're running only one instance of the game.

**Comment by CaioMGT** [comment]
> Any ETA on the release with the fix?

We're currently doing public testing of the new update in our discord, so you can grab a build there!

**Comment by A-noximous** [comment]
> > Any ETA on the release with the fix?
> 
> We're currently doing public testing of the new update in our discord, so you can grab a build there!

Thanks for the info! Will do so.
