### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by MCSmallCai** [IrisShaders/Iris#1817]
### Minecraft Version

Minecraft1.19.2

### Iris Version

iris-mc1.19.2-1.5.0

### Sodium Version

sodium-mc1.19.2-0.4.4

### Operating System

win11

### What is your GPU?

NVIDIA GeForce RTX 3050

### Java Version

java 17

### Reproduction Steps

Crash caused by "Chunks fade in" Update to the latest version chunksfadein - v3.0.5-1.19

Can be solved

**Comment by MCSmallCai** [comment]
I can enter the game after returning to version iris-1.4.5

**Comment by Lolothepro** [comment]
Seems to be a conflict with the mod named "C3H6N6O6"

**Comment by MCSmallCai** [comment]
> 似乎与名为“C3H6N6O6”的mod冲突
This mod was installed before, and I deleted it

**Comment by MCSmallCai** [comment]
I found it 
conflict with a mod named "MemoryLeakFix - v0.7.0 for 1.19"

**Comment by fxmorin** [comment]
MemoryLeakFix does not conflict, it simply loads all mixins during startup instead of when the classes are called. This means the crash will happen without MemoryLeakFix at a random point anyways

**Comment by coderbot16** [comment]
The crash report you've attached appears to have nothing to do with Iris. Could you attach a `latest.log` file from after a crash occurs?

**Comment by What42Pizza** [comment]
Something similar seems to be happening with Immersive Portals mod + Iris on 1.19.2. Iris 1.4.5 doesn't crash with Immersive Portals, but 1.5.0 does

**Comment by coderbot16** [comment]
Crashes with Immersive Portals are not linked to this issue and are resolved in the latest Immersive Portals release.

**Comment by What42Pizza** [comment]
No, the latest versions of Iris and Immersive portals still crash on 1.19.2 when put together. And it seems like this is linked because of how similar the conditions are

**Comment by coderbot16** [comment]
https://modrinth.com/mod/immersiveportals/version/2.4.4-1.19.3 is the latest version of Immersive Portals and contains a fix for the crashing. If it does not work then the fix didn't fully work and that would be a bug in Immersive Portals.

**Comment by coderbot16** [comment]
It looks like the issue report has been edited to be reporting a crash in Chunks Fade In. This is an issue caused by that mod injecting into internal Iris code that can change from version to version. The issue has been handled in their side: https://github.com/kerudion/chunksfadein/issues/18
