### ISSUE TITLE
[Incompatibility] ComputerCraft monitors to appear darker

### ISSUE THREAD

**Issue by hugeblank** [IrisShaders/Iris#1959]
### What happened?

The latest version of Iris (1.6.1) causes monitors to appear darker than they are without Iris. This issue occurs even when shaders are disabled. In 1.6.0 the issue is no longer there.

Originally reported in: https://github.com/cc-tweaked/CC-Tweaked/issues/1419

### Screenshots
1.6.1:
![image](https://user-images.githubusercontent.com/16393543/233742464-f5c19699-a0db-462d-8b13-3769c25f4df1.png)
1.6.0:
![image](https://user-images.githubusercontent.com/16393543/233793523-6573e8a4-c24b-443f-b2ad-351a2c3272bf.png)

### Log output

https://mclo.gs/f8VNoPP

### Minecraft Version

1.19.4

### Iris Version

iris-mc1.19.4-1.6.1

### Operating System

Arch Linux

### What is your GPU?

AMD Radeon RX 6600 XT

### Additional context

ComputerCraft Version: 1.104.0

**Comment by IMS212** [comment]
I likely broke the text sink again; will look into for 1.6.2.

**Comment by IMS212** [comment]
Fixed. https://github.com/IrisShaders/Iris/commit/06c4476b807f8b94134ea510c0d0560d6f3f86f4

**Comment by Ale32bit** [comment]
The issue is still present in v1.6.3.
Monitors appear darker only when shaders are disabled.
