### ISSUE TITLE
45-55% FPS Reduction using 1.21.5 compared to 1.21.4

### ISSUE THREAD

**Issue by ShadowFlandre** [IrisShaders/Iris#2732]
### What happened?

Unsure if it could be related to Sodium as well, but performance with shaders in 1.21.5 is halved (at least with my specs) compared to 1.21.4 despite higher fps average without shaders on. I think more testing on other configs needs to be done (I am kind of limited in this regard) but with my testing with Complimentary Reimagined (5.4 and 5.5.1 as well), my results are as follows...

NOTE: I also tried out Silders Enhanced Default, what should have been an easy 130 fps average in the past turned into 72 fps average from my quick testing, so its highly unlikely that this is an issue with the shader pack in question if this is consistent across 2 different shader packs now.

1.21.4:
No Shaders: 140 fps avg
Complimentary Reimagined: 47-55 fps avg
Silders Enhanced Default: 120-145 fps avg

1.21.5:
No Shaders: 269-271 fps avg
Complimentary Reimagined: 25-29 fps avg
Silders Enhanced Default: 71-75 fps avg

Specs:
Intel Core i7 8700
Nvidia GeForce GTX 1060 3GB
16 GB DDR4 2666 MHz
Windows 11 (have not tested Arch Linux yet)
JDK Version: Eclipse Temurin™ JDK 22
RAM Allocation: 2048 MiB Min, 10000 MiB Max
Shader pack settings preset: Custom (mostly low-medium though)
Test map seed: -4960670273589965778 (Large Biomes)
Command used for testing: /tp @p -517 120 632 0 40

Unsure as to what is the cause of this, but I urge performance testing to be done by others on the 1.21.5 build vs the 1.21.4 build. Could it be Sodium related? I'm not sure because I'm getting better performance without shaders when updating. Resource utilization looks to be roughly the same, though I seem to be using a bit less RAM overall, but that would definitely not explain -45% performance. If anyone can test these 2 versions and update the Issue, that would be cool and could probably give everyone more insight as to what's going on.

### Screenshots

1.21.4 Resource utilization:
![Image](https://github.com/user-attachments/assets/ceaf0383-53bb-40fb-a713-947f77bcef51)

1.21.5 Resource utilization:
![Image](https://github.com/user-attachments/assets/d339048c-5b66-44f7-9e01-0ae3cca21eb6)

### Minecraft Version

Minecraft 1.21.5

### Iris Version

1.8.11+mc1.21.5fabric

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce GTX 1060 3GB

**Comment by PBMINE** [comment]
This is true for Minecart 1.21.5 on Arch Linux.  In Minecraft 1.21.4, I experienced fps drops from 29 to 20 and a single-player world drop to around 15 from 30. I used the same settings for both the multiplayer world (smp) and the single-player world, including the same seed, coordinates, and settings, on an Intel HD 4600 with 949x509 resolution and bsl shader.

**Comment by ShadowFlandre** [comment]
I'll see if my brothers rig can replicate the issues

**Comment by danieltebor** [comment]
I have about 6 people on my server, including myself, confirming that FPS is cut in half on 1.21.5 compared to 1.21.4 when using Iris Shaders. This def needs to be a top-priority fix.

**Comment by D4NGER17** [comment]
I'm also having this same issue. Normally 85-97 fps in multiplayer server and around 130 fps in singleplayer, I now have around 52 fps in multiplayer and 68 fps in singleplayer. Oddly enough, the only shaderpack that doesn't do this large frame drop for me (instead it does less like a 25% fps drop) was Complementary_Unbound_5.2.1, which went from 88 in multiplayer to 68 after the new update. Even the newer versions of unbound shared this same 50% decline in frames. This is also happening to a few people I know.

**Comment by Ristovski** [comment]
Can confirm, seems like merely having the Iris rendering pipeline active increases the GPU load considerably: Even `skipAllRendering=true` (no difference between true/false) with bog standard [Base-330](https://github.com/shaderLABS/Base-330) shaders gives ~60% GPU load, whereas disabling shaders drops to 16% on a Vega integrated on a Ryzen 5700G, running `Mesa 24.2.4`.

**Comment by ShadowFlandre** [comment]
So this may in part be related to the fact 1.21.5 heavily rewrote a bunch of the rendering code per what IMS said in the Iris discord server. Honestly, it may just not be worth to fixing this until 1.21.6 releases where the rewritten rendering should mostly be ready. That being said I will still keep this open.

**Comment by desukia** [comment]
This is very real, I have the same problem

**Comment by Bipbip2109** [comment]
mc 1.21.6 w/ fabric 0.16.14, GraalVM JDK 24.0.1 G1GC 8G, NVIDIA RTX 2060 SUPER GPU, latest drivers (576.80).
I am also encountering this problem in a perfectly consistent manner. This issue should be marked as top priority.

**Comment by ShadowFlandre** [comment]
It likely wont be fixed for now, as attempting to fix it will likely break the very next update due to Mojang constantly rewriting rendering code as we speak for vibrant visuals.

**Comment by Bipbip2109** [comment]
The issue seems to have been fixed in version 1.9.1 (for both 1.21.6 and 1.21.7), confirmation from other testers would be appreciated.

**Comment by ShadowFlandre** [comment]
From my testing right now on 1.21.7 and 1.9.1 this is not fixed.

**Comment by Bipbip2109** [comment]
One of my friend who has an AMD 6750XT still has the issue. One other friend who has an AMD 7900XTX doesn't have it, and with an NVIDIA 2060 I don't seem to be affected by it anymore in iris 1.9.1
It seems to be dependent on the GPU/drivers.

**Comment by Yancey2023** [comment]
same problem. The FPS is 100 in 1.21.4 , but the FPS is 50 in 1.21.5.

**Comment by kotaru34** [comment]
same problem after updating to 1.21.6 from 1.21.4. My friend also has the exact same problem. We are both using sodium+iris with complementary reimagined

**Comment by FeldrinH** [comment]
The performance has not improved meaningfully in 1.21.8 either. Also, this and https://github.com/IrisShaders/Iris/issues/2818 are probably the same issue.

**Comment by slonkazoid** [comment]
#2790 is related too

**Comment by reChords25** [comment]
I have the same issue, I am playing 1.21.6. What's interesting: When I change my render distance in 1.21.4 with shaders turned on, the fps vary a lot. Which, of course, makes sense and is the expected behavior. But on 1.21.6 this does NOT happen, at least not nearly as much. Going from 20 chunks render distance to 10 barely changes fps by 10. All the settings are the same, as I just updated the mods and kept the settings files.

I run an AMD Ryzen 5800x with 32GB of RAM, Nvidia RTX 3060 12G and Java 21.0.3.

**Comment by Aleksanaa** [comment]
Same with Ryzen 7 7840HS and integrated graphics

**Comment by David-WXYZ** [comment]
Having this same issue with a NVIDIA RTX GPU and Complementary Shaders. About a 40% reduction in FPS going from 1.21.4 to 1.21.5. Would really love to see this fixed.

**Comment by Pumpk1in** [comment]
Mhh, I was wondering why my performance were so bad after upgrading from 1.21.4 to 1.21.10
I suppose we all are in the same boat for now...

**Comment by mcnuggetsx20** [comment]
I'm having the same issue as well. Specs:
Arch Linux (zen kernel)
NVIDIA GTX 1660Ti (closed source drivers)

From 100 fps in 1.21.4 the performance drops significantly to 40-50 fps in 1.21.5+. Important to note, that the GPU utilization stays at 100% so underutilization can be ruled out.

**Comment by kotaru34** [comment]
- [ ] Looks like it will not be fixed. All the people leading here from search engines should consider playing without shaders or fall back to 1.21.4

**Comment by amayra** [comment]
what is the problem is exactly?

**Comment by mcnuggetsx20** [comment]
> what is the problem is exactly?

I mean it says it in the title. Using shaders with Iris on 1.21.5+ is roughly half as fast as it is on 1.21.4.

**Comment by jkazimierczak** [comment]
Could be related: https://bugs.mojang.com/browse/MC/issues/MC-295893
At the same time, some people reported having more luck with https://modrinth.com/mod/immediatelyfast installed. It does nothing for me on GTX 1060 6GB, OC-ed. I'm having the same issue:
- 1.21.4 ~ 50 FPS
- 1.21.10 ~ 30 FPS

Details:
- GPU: GTX 1060 6GB,
- Windows 10,
- Minecraft 1.21.10,
- Iris 1.9.6+mc1.21.9

@kotaru34 where did you get that information from (that "it will not be fixed")?

**Comment by Samalando** [comment]
This is an issue with vanilla Minecraft and affects all performance, not just shaders. Mojang is changing a lot of the rendering system in preparation for Vibrant Visuals, which has led to these issues. It is currently not known when mojang will fix these issues. (or if they will)

**Comment by ShadowFlandre** [comment]
This issue seems for the most part to be resolved as result of the discovery of #2940 albeit not perfect. The only thing I've changed in this testing since the initial bug report was using ZGC instead of the default G1 GC but average FPS using Iris 1.10.3 for 1.21.11 has gone up to 37-51 average FPS. The FPS feels very close to 1.21.4 when on the ground but it seems that fps is a bit lower still if you are high up rendering a ton of chunks, and this could be due to https://bugs.mojang.com/browse/MC/issues/MC-295893 but the main culprit was the mismatch in polygon type in HorizonRenderer.java rendering way more triangles than necessary as a result.

TLDR - I am going to close this bug report as the main issue has been solved. My recommendation; please update to Minecraft 1.21.11 and Iris 1.10.3 as soon as possible if you want most of your performance back and performance likely will improve once more fixes are done on Mojang's part in the future.
