### ISSUE TITLE
Iris sodium-compatibility glowing effect issue

### ISSUE THREAD

**Issue by KpauMupa** [IrisShaders/Iris#79]
![изображение](https://user-images.githubusercontent.com/76217453/104092739-00afe980-5297-11eb-9d2b-54e8a072715d.png)

This was an item with glowing effect. Iris mod renders it in a strange way...

**Comment by KpauMupa** [comment]
sildur's vibrant lite

**Comment by coderbot16** [comment]
I think that this happens on OptiFine as well, it seems to be a common issue on shaderpacks. Can you verify that this happens on OF too?

**Comment by KpauMupa** [comment]
![2021-01-10_07 20 26](https://user-images.githubusercontent.com/76217453/104114382-d6047600-5314-11eb-894a-457509e3c1dd.png)
With optifine glowing effect doesn't work at all 0_0
Same shaders. It doesn't matter if Fast Render is on/off.

I think it's better to see the glowing effect, even if it's broken, rather not to see completely.

**Comment by coderbot16** [comment]
Fixed!

![2021-02-25_13 53 33](https://user-images.githubusercontent.com/22420959/109224789-45bdab80-7771-11eb-8107-a6e3e74d0558.png)

**Comment by RwOnke** [comment]
Doesn't glow for me, im using sodium 1.20.6 with iris shaders. I tried BSL shaders and complementaryReimagined

**Comment by Kasprenius** [comment]
I'm still not seeing it using Complimentary Unbound + Euphoria Patches
