### ISSUE TITLE
Sildurs Vibrant: Crying Obsidian tear particles render as magenta.

### ISSUE THREAD

**Issue by thedocruby** [IrisShaders/Iris#88]
As shown below, the tears from Crying Obsidian blocks generate in a magenta color, instead of the default purple:
![2021-01-21_11 05 28](https://user-images.githubusercontent.com/76263371/105386702-b574cf80-5be2-11eb-80db-c4ef5aca52fc.png)
Whether this is an issue with coloration, textures, or just an extreme case of faulty particle lighting washing out the color, I cannot say. I can however make the claim that the other drip particles do not seem to be affected by this:
![2021-01-21_11 55 08](https://user-images.githubusercontent.com/76263371/105386770-cb829000-5be2-11eb-88ec-c6471273ecb1.png)
![2021-01-21_11 59 17](https://user-images.githubusercontent.com/76263371/105386794-d4736180-5be2-11eb-8521-1de01b484131.png)

I am using Iris and Sildurs Vibrant High, on 1.16.4, with no Sodium.

**Comment by coderbot16** [comment]
Can you re-check this on the latest version of Iris? I think this should be fixed.

**Comment by yitzy299** [comment]
![image](https://user-images.githubusercontent.com/66269211/109697826-9aed2900-7b86-11eb-8043-09c5a32a56ed.png)
Still present in the latest sodium-compat commit

**Comment by coderbot16** [comment]
How do they render on OptiFine?

**Comment by yitzy299** [comment]
![image](https://user-images.githubusercontent.com/66269211/109698738-9f661180-7b87-11eb-9139-4014a2d926a9.png)
Slightly more purple I think

**Comment by coderbot16** [comment]
Inspection in an image editor reveals that the particle in shadow in the OptiFine image has almost the exact same colors as the particles in the Iris image (#C60349 vs #C60348). The particles in sun have a different color, but that is expected. Try disabling shadows on both OptiFine and Iris, use the same world, and use `/gamerule doDaylightCycle false` and `/time set day`. You should observe that the particles have the same color.

**Comment by thedocruby** [comment]
Aren't they purple like the texture when using vanilla rendering? If so, is it an OptiFine bug or Sildurs bug?

**Comment by coderbot16** [comment]
It's likely either a bug or deliberate choice in Sildur's Vibrant Shaders, I don't think this is an issue in OptiFine or Iris. Unless a similar color issue happens on the Iris internal shaders, I don't think this is an Iris issue.

I should note that the particle rendering *was* wrong on Sildur's Vibrant compared to OptiFine previously, however the issue I saw originally (particles giving off excessive bloom) was fixed in a more recent commit to trunk.

If proof emerges that the color is indeed an Iris or OptiFine issue, I'll reopen this issue, but I will close it for now.
