### ISSUE TITLE
Custom fragment shader outputs are not supported on 1.17.1+ (needed by Nostalgia Shaders, Vanilla Plus Shaders, etc)

### ISSUE THREAD

**Issue by LizIsTired** [IrisShaders/Iris#937]
### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9.jar for 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 11

### What is your GPU?

AMD Radeon R9 270X

### Java Version

Java 16

### Reproduction Steps

Trying to render anything with [Nostalgia Shaders ](https://www.curseforge.com/minecraft/customization/nostalgia-shader/files/3468375) (either by enabling shaders while loaded in a world or with shaders already enabled) makes the game immediately crash
[crash-2021-10-18_08.22.50-client.txt](https://github.com/IrisShaders/Iris/files/7369527/crash-2021-10-18_08.22.50-client.txt)
[2021-10-18-3.log](https://github.com/IrisShaders/Iris/files/7369529/2021-10-18-3.log)

**Comment by coderbot16** [comment]
I believe that this might have been resolved with the merge of https://github.com/IrisShaders/Iris/pull/967.

**Comment by LizIsTired** [comment]
Using Nostalgia 3.1 on latest commit for 1.18 with no difference, still crashes
[latest.log](https://github.com/IrisShaders/Iris/files/7749717/latest.log)

**Comment by coderbot16** [comment]
Also needed for SoftVoxels by RRe36

**Comment by IMS212** [comment]
Fixed.
